DROP TABLE IF EXISTS paises;
DROP TABLE IF EXISTS seleçoes;
DROP TABLE IF EXISTS jogadores;
DROP TABLE IF EXISTS estadios;
DROP TABLE IF EXISTS partidas;
DROP TABLE IF EXISTS grupo;

CREATE TABLE paises(
    id_pais VARCHAR(100) UNIQUE PRIMARY KEY,
    nome_pais VARCHAR(100),
    sigla_pais VARCHAR(3)
  );
  
 CREATE TABLE seleçoes(
 	id_seleçao VARCHAR(100) UNIQUE PRIMARY KEY,
   	nome_seleçao VARCHAR(100),
   	continente_selecao VARCHAR(100),
   	técnico VARCHAR(100)
 );
 
 CREATE TABLE jogadores(
 	id_jogador VARCHAR(100) UNIQUE PRIMARY KEY,
   	nome_jogador VARCHAR(100),
   	posição_jogador VARCHAR(3),
   	num_camisa INT,
   	nacionalidade VARCHAR(100),
   
   	FOREIGN KEY (nacionalidade) REFERENCES seleçoes(nome_seleçao)
 );
 
 CREATE TABLE estadios(
 	id_estadio VARCHAR(100) UNIQUE PRIMARY KEY,
   	nome_estadio VARCHAR(100),
   	cidade_estadio VARCHAR(100),
   	pais_estadio VARCHAR(100),
   
   	FOREIGN key (pais_estadio) REFERENCES paises(nome_pais)
 );
 
 CREATE TABLE partidas(
 	id_partida VARCHAR(100) UNIQUE PRIMARY KEY,
   	data_partida DATE,
   	horario_partida TIME(0),
   	nome_estadio VARCHAR(100),
   	selecao_m VARCHAR(100),
   	selecao_v VARCHAR(100),
   	placar VARCHAR(50),
   	fase_campeonato VARCHAR(50),
   
   	FOREIGN key (nome_estadio) REFERENCES estadios(nome_estadio),
   	FOREIGN key (selecao_m) REFERENCES seleções(nome_seleçao),
   	FOREIGN key (selecao_v) REFERENCES seleções(nome_seleçao)
 );
 
 CREATE TABLE grupos(
 	id_grupo VARCHAR(100) UNIQUE PRIMARY KEY,
   	nome_grupo VARCHAR(100)
 );
 
 
 -- ADICIONA PAÍSES CEDE --
 INSERT INTO paises(id_pais, nome_pais, sigla_pais) VALUES
 ('EUA - ESTADOS UNIDOS', 'ESTADOS UNIDOS', 'EUA'),
 ('CAN - CANADA', 'CANADA', 'CAN'),
 ('MEX - MEXICO', 'MEXICO', 'MEX');
 
 -- ADICIONA SELEÇÕES --
 INSERT INTO seleçoes(id_seleçao, nome_seleçao, continente_selecao, técnico) VALUES
 ('BRA - BRASIL', 'BRASIL', 'AMERICA DO SUL', 'CARLO ANCELLOTI'),
 ('MAR - MARROCOS', 'MARROCOS', 'AFRICA', 'MOHAMED OUAHBI'),
 ('SCO - ESCOCIA', 'ESCOCIA', 'EUROPA', 'STEVE CLARKE'),
 ('HAI - HAITI', 'HAITI', 'AMERICA CENTRAL', 'SEBASTIEN MIGNES');
 
 -- ADICONA JOGADORES --
 INSERT INTO jogadores(id_jogador, nome_jogador, posição_jogador, num_camisa, nacionalidade) VALUES
 -- BRASIL --
 ('01_BRA_ALISSON', 'ALISSON', 'GL', '01', 'BRASIL'),
 ('23_BRA_EDERSON', 'EDERSOON', 'GL', '23', 'BRASIL'),
 ('12_BRA_WEVERTON', 'WEVERTON', 'GL', '12', 'BRASIL'),
 
 ('06_BRA_ALEX-SANDRO', 'ALEX SANDRO', 'DEF', '06', 'BRASIL'),
 ('14_BRA_BREMER', 'BREMER', 'DEF', '14', 'BRASIL'),
 ('13_BRA_DANILO', 'DANILO', 'DEF', '13', 'BRASIL'),
 ('16_BRA_DOUGLAS-SANTOS', 'DOUGLAS SANTOS', 'DEF', '16', 'BRASIL'),
 ('03_BRA_GABRIEL-MAGALHAES', 'GABRIEL MAGALHAES', 'DEF', '03', 'BRASIL'),
 ('24_BRA_IBANEZ', 'IBANEZ', 'DEF', '24', 'BRASIL'),
 ('15_BRA_LEO-PEREIRA', 'LEO PEREIRIRA', 'DEF', '15', 'BRASIL'),
 ('04_BRA_MARQUINHOS', 'MARQUINHOS', 'DEF', '04', 'BRASIL'),
 ('43_BRA_WESLEY', 'WESLEY', 'DEF', '43', 'BRASIL'),
 
 ('08_BRA_BRUNO-GUIMARAES', 'BRUNO GUIMARAES', 'MEI', '08', 'BRASIL'),
 ('05_BRA_CASEMIRO', 'CASEMIRO', 'MEI', '05', 'BRASIL'),
 ('18_BRA_DANILO', 'DANILO', 'MEI', '18', 'BRASIL'),
 ('17_BRA_FABINHO', 'FABINHO', 'MEI', '17', 'BRASIL'),
 ('20_BRA_PAQUETA', 'PAQUETA', 'MEI', '20', 'BRASIL'),
 
 ('19_BRA_ENDRICK', 'ENDRICK', 'ATA', '19', 'BRASIL'),
 ('22_BRA_MARTINELLI', 'MARTINELLI', 'ATA', '22', 'BRASIL'),
 ('09_BRA_IGOR-THIAGO', 'IGOR THIAGO', 'ATA', '09', 'BRASIL'),
 ('21_BRA_LUIZ-HENRIQUE', 'LUIZ HENRIQUE', 'ATA', '21', 'BRASIL'),
 ('22_BRA_MATHEUS-CUNHA', 'MATHEUS CUNHA', 'ATA', '22', 'BRASIL'),
 ('11_BRA_RAPHINHA', 'RAPHINHA', 'ATA', '11', 'BRASIL'),
 ('26_BRA_RAYAN', 'RAYAN', 'ATA', '26', 'BRASIL'),
 ('07_BRA_VINI-JR', 'VINI JR', 'ATA', '07', 'BRASIL'),
 ('10_BRA_NEYMAR-JR', 'NEYMAR JR', 'ATA', '10', 'BRASIL'),
 
 -- MARROCOS
('01_MAR_BONO', 'BONO', 'GL', '01', 'MARROCOS'),
('12_MAR_MOHAMEDI', 'MOHAMEDI', 'GL', '12', 'MARROCOS'),
('23_MAR_TAGNAOUTI', 'TAGNAOUTI', 'GL', '23', 'MARROCOS'),

('02_MAR_HAKIMI', 'HAKIMI', 'DEF', '02', 'MARROCOS'),
('03_MAR_MAZRAOUI', 'MAZRAOUI', 'DEF', '03', 'MARROCOS'),
('04_MAR_SAISS', 'SAISS', 'DEF', '04', 'MARROCOS'),
('05_MAR_AGUERD', 'AGUERD', 'DEF', '05', 'MARROCOS'),
('06_MAR_HARKASS', 'HARKASS', 'DEF', '06', 'MARROCOS'),
('13_MAR_HAKIM', 'HAKIM', 'DEF', '13', 'MARROCOS'),
('24_MAR_ATIAT-ALLAH', 'ATIAT ALLAH', 'DEF', '24', 'MARROCOS'),

('08_MAR_OUNAHI', 'OUNAHI', 'MEI', '08', 'MARROCOS'),
('10_MAR_AMRABAT', 'AMRABAT', 'MEI', '10', 'MARROCOS'),
('14_MAR_EL-KHANNOUSS', 'EL KHANNOUSS', 'MEI', '14', 'MARROCOS'),
('15_MAR_RICHARDSON', 'RICHARDSON', 'MEI', '15', 'MARROCOS'),
('18_MAR_AMALLAH', 'AMALLAH', 'MEI', '18', 'MARROCOS'),

('07_MAR_ZIYECH', 'ZIYECH', 'ATA', '07', 'MARROCOS'),
('09_MAR_EN-NESYRI', 'EN NESYRI', 'ATA', '09', 'MARROCOS'),
('11_MAR_ABDE', 'ABDE', 'ATA', '11', 'MARROCOS'),
('17_MAR_RAHIMI', 'RAHIMI', 'ATA', '17', 'MARROCOS'),
('19_MAR_ADLI', 'ADLI', 'ATA', '19', 'MARROCOS'),

-- ESCOCIA
('01_ESC_GORDON', 'GORDON', 'GL', '01', 'ESCOCIA'),
('12_ESC_KELLY', 'KELLY', 'GL', '12', 'ESCOCIA'),
('23_ESC_GUNN', 'GUNN', 'GL', '23', 'ESCOCIA'),

('02_ESC_PATTERSON', 'PATTERSON', 'DEF', '02', 'ESCOCIA'),
('03_ESC_ROBERTSON', 'ROBERTSON', 'DEF', '03', 'ESCOCIA'),
('04_ESC_HENDRY', 'HENDRY', 'DEF', '04', 'ESCOCIA'),
('05_ESC_MCTOMINAY', 'MCTOMINAY', 'DEF', '05', 'ESCOCIA'),
('06_ESC_TIERNEY', 'TIERNEY', 'DEF', '06', 'ESCOCIA'),
('13_ESC_PORTOUS', 'PORTOUS', 'DEF', '13', 'ESCOCIA'),
('15_ESC_COOPER', 'COOPER', 'DEF', '15', 'ESCOCIA'),

('08_ESC_MCGREGOR', 'MCGREGOR', 'MEI', '08', 'ESCOCIA'),
('10_ESC_GILMOUR', 'GILMOUR', 'MEI', '10', 'ESCOCIA'),
('14_ESC_ARMSTRONG', 'ARMSTRONG', 'MEI', '14', 'ESCOCIA'),
('16_ESC_MCGINN', 'MCGINN', 'MEI', '16', 'ESCOCIA'),
('18_ESC_CHRISTIE', 'CHRISTIE', 'MEI', '18', 'ESCOCIA'),

('07_ESC_ADAMS', 'ADAMS', 'ATA', '07', 'ESCOCIA'),
('09_ESC_DYKES', 'DYKES', 'ATA', '09', 'ESCOCIA'),
('11_ESC_FOREST', 'FOREST', 'ATA', '11', 'ESCOCIA'),
('17_ESC_SHANKLAND', 'SHANKLAND', 'ATA', '17', 'ESCOCIA'),
('19_ESC_DOAK', 'DOAK', 'ATA', '19', 'ESCOCIA'),

-- HAITI
('01_HAI_PLACIDE', 'PLACIDE', 'GL', '01', 'HAITI'),
('12_HAI_ALEXANDRE', 'ALEXANDRE', 'GL', '12', 'HAITI'),
('23_HAI_JOSEPH', 'JOSEPH', 'GL', '23', 'HAITI'),

('02_HAI_PIERRE', 'PIERRE', 'DEF', '02', 'HAITI'),
('03_HAI_ADE', 'ADE', 'DEF', '03', 'HAITI'),
('04_HAI_DUVERNE', 'DUVERNE', 'DEF', '04', 'HAITI'),
('05_HAI_LAMBERT', 'LAMBERT', 'DEF', '05', 'HAITI'),
('06_HAI_JEAN', 'JEAN', 'DEF', '06', 'HAITI'),
('13_HAI_FRANCOIS', 'FRANCOIS', 'DEF', '13', 'HAITI'),
('15_HAI_BELIZAIRE', 'BELIZAIRE', 'DEF', '15', 'HAITI'),

('08_HAI_PIERROT', 'PIERROT', 'MEI', '08', 'HAITI'),
('10_HAI_LOUIS', 'LOUIS', 'MEI', '10', 'HAITI'),
('14_HAI_NAZON', 'NAZON', 'MEI', '14', 'HAITI'),
('16_HAI_JACQUES', 'JACQUES', 'MEI', '16', 'HAITI'),
('18_HAI_CHERY', 'CHERY', 'MEI', '18', 'HAITI'),

('07_HAI_GUERRIER', 'GUERRIER', 'ATA', '07', 'HAITI'),
('09_HAI_PIERROT', 'PIERROT', 'ATA', '09', 'HAITI'),
('11_HAI_BAZILE', 'BAZILE', 'ATA', '11', 'HAITI'),
('17_HAI_DANLEY', 'DANLEY', 'ATA', '17', 'HAITI'),
('19_HAI_MONDESIR', 'MONDESIR', 'ATA', '19', 'HAITI');

INSERT INTO estadios(id_estadio, nome_estadio, cidade_estadio,pais_estadio) VALUES
--ESTÁDIOS DO CANADÁ--
('01_ESTADIO_CAN', 'BMO FIELD', 'TORONTO', 'CANADA'),
('02_ESTADIO_CAN', 'BC PLACE', 'VANCOUVER', 'CANADA'),

--ESTÁDIOS DO MÉXICO--
('03_ESTADIO_MEX', 'ESTADIO AZTECA', 'CIDADE DO MEXICO', 'MEXICO'),
('04_ESTADIO_MEX', 'ESTADIO AKRON', 'GUADALAJARA', 'MEXICO'),
('05_ESTADIO_MEX', 'ESTADIO BBVA', 'MONTERREY', 'MEXICO'),

--ESTÁDIOS DO ESTADOS UNIDOS--
('06_ESTADIO_EUA', 'MERCEDES-BENZ STADIUM', 'ATLANTA', 'ESTADOS UNIDOS'),
('07_ESTADIO_EUA', 'GILLETTE STADIUM', 'FOXBOROUGH', 'ESTADOS UNIDOS'),
('08_ESTADIO_EUA', 'AT&T STADIUM', 'ARLINGTON', 'ESTADOS UNIDOS'),
('09_ESTADIO_EUA', 'NRG STADIUM', 'HOUSTON', 'ESTADOS UNIDOS'),
('10_ESTADIO_EUA', 'ARROWHEAD STADIUM', 'KANSAS CITY', 'ESTADOS UNIDOS'),
('11_ESTADIO_EUA', 'SOFI STADIUM', 'INGLEWOOD', 'ESTADOS UNIDOS'),
('12_ESTADIO_EUA', 'HARD ROCK STADIUM', 'MIAMI GARDENS', 'ESTADOS UNIDOS'),
('13_ESTADIO_EUA', 'METLIFE STADIUM', 'EAST RUTHERFORD', 'ESTADOS UNIDOS'),
('14_ESTADIO_EUA', 'LINCOLN FINANCIAL FIELD', 'FILADELFIA', 'ESTADOS UNIDOS'),
('15_ESTADIO_EUA', 'LEVIS STADIUM', 'SANTA CLARA', 'ESTADOS UNIDOS'),
('16_ESTADIO_EUA', 'LUMEN FIELD', 'SEATTLE', 'ESTADOS UNIDOS');
 

INSERT INTO partidas(id_partida, data_partida, horario_partida, nome_estadio, selecao_m, selecao_v, placar, fase_campeonato) VALUES
-- FASE DE GRUPOS | GRUPO C --
('P01_GRUPO_C', '2026-06-13', '19:00', 'METLIFE STADIUM', 'BRASIL', 'MARROCOS', '3x1', 'FASE DE GRUPOS'),

('P02_GRUPO_C', '2026-06-13', '22:00', 'GILLETTE STADIUM', 'HAITI', 'ESCOCIA', '2x0', 'FASE DE GRUPOS'),

('P03_GRUPO_C', '2026-06-19', '19:00', 'GILLETTE STADIUM', 'ESCOCIA', 'MARROCOS', '2x2', 'FASE DE GRUPOS'),

('P04_GRUPO_C', '2026-06-19', '21:30', 'LINCOLN FINANCIAL FIELD', 'BRASIL', 'HAITI', '1x0', 'FASE DE GRUPOS'),

('P05_GRUPO_C', '2026-06-24', '19:00', 'MERCEDES-BENZ STADIUM', 'MARROCOS', 'HAITI', '4x0', 'FASE DE GRUPOS'),

('P06_GRUPO_C', '2026-06-24', '19:00', 'HARD ROCK STADIUM', 'ESCOCIA', 'BRASIL', '2x3', 'FASE DE GRUPOS');


INSERT INTO grupos(id_grupo,nome_grupo) VALUES
('GRUPO-A', 'GRUPO A'),
('GRUPO-B', 'GRUPO B'),
('GRUPO-C', 'GRUPO C'),
('GRUPO-D', 'GRUPO D'),
('GRUPO-E', 'GRUPO E'),
('GRUPO-F', 'GRUPO F'),
('GRUPO-G', 'GRUPO G'),
('GRUPO-H', 'GRUPO H'),
('GRUPO-I', 'GRUPO I'),
('GRUPO-J', 'GRUPO J'),
('GRUPO-K', 'GRUPO K'),
('GRUPO-L', 'GRUPO L');
 
SELECT * FROM paises;
SELECT * FROM jogadores;
SELECT * FROM estadios;
SELECT * FROM partidas;
SELECT * FROM grupos;